### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [dennisdebel/pi_dj#1]
Hello!

I found link to this project from https://hackaday.com/2020/07/03/djing-without-the-truckload-of-equipment-secret-ingredient-is-raspberry-pi/

Could you please add information about license of this repository — is it allowed to copy, change and use code in any purpose?

As I understand, most of your files are based on Mixxx files, which is GPL-2+ licensed, but files `res/skins/LateNight*/*` are "Attribution-ShareAlike 4.0 International" and derivative work should be distributed under the same license. You can find this information in the file `/usr/share/doc/mixxx/copyright` of your Debian-based OS:

```
Files: *
Copyright:
 2001-2016 Mixxx development team
 2010 Jeff Nelson <dj.synth@gmail.com>
 2008 Mark Hills <mark@pogo.org.uk>
 2008 by Garth Dahlstrom <ironstorm@users.sf.net>
 2002-2007 Tim Goetze <tim@quitte.de>
 2006 David Yeh <dtyeh@ccrma.stanford.edu>
 2003 by Svein Magne Bang
 2002,2003 Erik de Castro Lopo <erikd@mega-nerd.com>
 2000-2002 Richard W.E. Furse
License: GPL-2+

…

Files: res/skins/LateNight*/*
 res/skins/Deere*/*
 res/skins/Shade*/*
Copyright: 2010 jus <jus@justmail.de>
License: CC-BY-SA
 Attribution-ShareAlike 4.0 International
```

So maybe your repository should have mixed license, like in Debian package.

Please ping me if you need any help here.

**Comment by dennisdebel** [comment]
Hi!

Thanks for your message! It should be mixed then I think!
How would I go about that?
Dennis

**Comment by vazhnov** [comment]
@dennisdebel, let's try this one: https://github.com/dennisdebel/pi_dj/pull/2
