### ISSUE TITLE
Blog post for the Mixxx Website

### ISSUE THREAD

**Issue by Holzhaus** [dennisdebel/pi_dj#3]
First of all sorry for abusing your issue tracker. Unfortunately GitHub doesn't have a convenient way to message someone ;-)

This is a very cool project. We saw the [demo video on Reddit](https://redd.it/hg5gr4) and liked it very much. Are you interested in writing a small blog post for [our website](https://mixxx.org) that explains how you got the idea, what issues you faced and how you solved them and how you're using the end result? If so, please contact us via [Zulip Chat](https://mixxx.zulipchat.com/) or just file a PR against the [mixxxdj/website repo](https://github.com/mixxxdj/website).

**Comment by Be-ing** [comment]
The blog on our website uses Markdown, so it should be pretty easy to adapt what you've already written.

**Comment by dennisdebel** [comment]
Ha, thanks for re-appropriating the issue tracker! Sure thing! See you on Zulip!

**Comment by vazhnov** [comment]
Just for history, link to the post: https://mixxx.org/news/2020-08-22-portable-mixxx-setup/
